const Filters = {
  experiment: [
    {
      expectedName: 'creatorName',
      hint: 'User name',
      type: 'text',
      value: 'user',
    },
    {
      expectedName: 'name',
      hint: 'Experiment name',
      type: 'text',
      value: 'name',
    },
    {
      expectedName: 'type',
      hint: 'Screen type',
      type: 'text',
      value: 'type',
    },
    {
      expectedName: 'timepoint',
      hint: 'Time Point',
      type: 'text',
      value: 'timepoint',
    },
    {
      expectedName: 'creationDate',
      hint: 'Start date',
      place: 'start',
      type: 'date',
      value: 'startDate',
    },
    {
      expectedName: 'creationDate',
      hint: 'End date',
      place: 'end',
      type: 'date',
      value: 'endDate',
    },
  ],
  microscopy: [
    {
      expectedName: 'creatorName',
      hint: 'User name',
      type: 'text',
      value: 'user',
    },
    {
      expectedName: 'name',
      hint: 'Sample name',
      type: 'text',
      value: 'name',
    },
    {
      expectedName: 'type',
      hint: 'Screen type',
      type: 'text',
      value: 'type',
    },
    {
      expectedName: 'replicate',
      hint: 'Replicate',
      type: 'text',
      value: 'replicate',
    },
    {
      expectedName: 'concentration',
      hint: 'Concentration',
      type: 'text',
      value: 'concentration',
    },
    {
      expectedName: 'timepoint',
      hint: 'Time Point',
      type: 'text',
      value: 'timepoint',
    },
    {
      expectedName: 'microscope',
      hint: 'Microscope',
      type: 'text',
      value: 'microscope',
    },
    {
      expectedName: 'channels',
      hint: 'Marker/antibody',
      type: 'object',
      value: 'channels',
    },
    {
      expectedName: 'creationDate',
      hint: 'Start date',
      place: 'start',
      type: 'date',
      value: 'startDate',
    },
    {
      expectedName: 'creationDate',
      hint: 'End date',
      place: 'end',
      type: 'date',
      value: 'endDate',
    },
  ],
  project: [
    {
      expectedName: 'creatorName',
      hint: 'User name',
      type: 'text',
      value: 'user',
    },
    {
      expectedName: 'name',
      hint: 'Project name',
      type: 'text',
      value: 'name',
    },
    {
      expectedName: 'creationDate',
      hint: 'Start date',
      place: 'start',
      type: 'date',
      value: 'startDate',
    },
    {
      expectedName: 'creationDate',
      hint: 'End date',
      place: 'end',
      type: 'date',
      value: 'endDate',
    },
  ],
  sample: [
    {
      expectedName: 'creatorName',
      hint: 'User name',
      type: 'text',
      value: 'user',
    },
    {
      expectedName: 'name',
      hint: 'Sample name',
      type: 'text',
      value: 'name',
    },
    {
      expectedName: 'type',
      hint: 'Screen type',
      type: 'text',
      value: 'type',
    },
    {
      expectedName: 'replicate',
      hint: 'Replicate',
      type: 'text',
      value: 'replicate',
    },
    {
      expectedName: 'concentration',
      hint: 'Concentration',
      type: 'text',
      value: 'concentration',
    },
    {
      expectedName: 'timepoint',
      hint: 'Time Point',
      type: 'text',
      value: 'timepoint',
    },
    {
      expectedName: 'creationDate',
      hint: 'Start date',
      place: 'start',
      type: 'date',
      value: 'startDate',
    },
    {
      expectedName: 'creationDate',
      hint: 'End date',
      place: 'end',
      type: 'date',
      value: 'endDate',
    },
  ],
  screen: [
    {
      expectedName: 'creatorName',
      hint: 'User name',
      type: 'text',
      value: 'user',
    },
    {
      expectedName: 'name',
      hint: 'Screen name',
      type: 'text',
      value: 'name',
    },
    {
      expectedName: 'type',
      hint: 'Screen Type',
      options: [
        {
          text: 'CRISPR',
          value: 'CRISPR',
        },
        {
          text: 'generic',
          value: 'generic',
        },
      ],
      type: 'select',
      value: 'type',
    },
    {
      expectedName: 'species',
      hint: 'Species',
      type: 'text',
      value: 'species',
    },
    {
      expectedName: 'taxonID',
      hint: 'TaxonID',
      type: 'number',
      value: 'taxonID',
    },
    {
      expectedName: 'cell',
      hint: 'Cell type',
      type: 'text',
      value: 'cell',
    },
    {
      expectedName: 'cellID',
      hint: 'Cell ID',
      type: 'text',
      value: 'cellID',
    },
    {
      expectedName: 'cellMods',
      hint: 'Cell modifications',
      type: 'arrString',
      value: 'cellMods',
    },
    {
      expectedName: 'drugs',
      hint: 'Drugs',
      type: 'arrNumber',
      value: 'drugs',
    },
    {
      expectedName: 'condition',
      hint: 'Condition',
      type: 'text',
      value: 'condition',
    },
    {
      expectedName: 'creationDate',
      hint: 'Start date',
      place: 'start',
      type: 'date',
      value: 'startDate',
    },
    {
      expectedName: 'creationDate',
      hint: 'End date',
      place: 'end',
      type: 'date',
      value: 'endDate',
    },
  ],
};
export default Filters;
